GET localhost:9090/order

###
PUT localhost:9090/order
Content-Type: application/json

{
  "customerId": 1012,
  "items": [
    {
      "name": "hamburger",
      "quantity": 5
    },
    {
      "name": "cheeseburger",
      "quantity": 2
    },
    {
      "name": "mc-spicy",
      "quantity": 10
    },
    {
      "name": "spicy-stripes",
      "quantity": 20
    },
    {
      "name": "ice-cream",
      "quantity": 2
    }
  ]
}